name: Node CI

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: [Server] Install Dependencies
      working-directory: ./server
      run: npm ci
    - name: [Server] Build
      working-directory: ./server
      run: npm run build --if-present
    - name: [Client] Install Dependencies
      working-directory: ./client
      run: npm ci
    - name: [Client] Build
      working-directory: ./client
      run: npm run build --if-present